[2025-06-06T19:43:41.480+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:28:56.079507+00:00/task_id=merge_data permission to 509
[2025-06-06T19:43:41.480+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:28:56.079507+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:28:56.079507+00:00/task_id=merge_data'
[2025-06-06T19:43:41.499+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:28:56.079507+00:00/task_id=merge_data permission to 509
[2025-06-06T19:43:41.499+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:28:56.079507+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:28:56.079507+00:00/task_id=merge_data'
[2025-06-06T19:43:41.525+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_music_pipeline.merge_data manual__2025-06-06T19:28:56.079507+00:00 [queued]>
[2025-06-06T19:43:41.531+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_music_pipeline.merge_data manual__2025-06-06T19:28:56.079507+00:00 [queued]>
[2025-06-06T19:43:41.531+0000] {taskinstance.py:2170} INFO - Starting attempt 5 of 6
[2025-06-06T19:43:41.540+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): merge_data> on 2025-06-06 19:28:56.079507+00:00
[2025-06-06T19:43:41.545+0000] {standard_task_runner.py:60} INFO - Started process 2525 to run task
[2025-06-06T19:43:41.547+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_music_pipeline', 'merge_data', 'manual__2025-06-06T19:28:56.079507+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpz69949v8']
[2025-06-06T19:43:41.549+0000] {standard_task_runner.py:88} INFO - Job 94: Subtask merge_data
[2025-06-06T19:43:41.587+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:28:56.079507+00:00/task_id=merge_data permission to 509
[2025-06-06T19:43:41.588+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:28:56.079507+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=etl_music_pipeline/run_id=manual__2025-06-06T19:28:56.079507+00:00/task_id=merge_data'
[2025-06-06T19:43:41.589+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_music_pipeline.merge_data manual__2025-06-06T19:28:56.079507+00:00 [running]> on host 3dc3cd419f05
[2025-06-06T19:43:41.645+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_music_pipeline' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T19:28:56.079507+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T19:28:56.079507+00:00'
[2025-06-06T19:43:41.646+0000] {etl_pipeline.py:25} INFO - [START] Task: merge_data
[2025-06-06T19:43:41.647+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 26, in wrapper
    result = func(*args, **kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 33, in wrapper
    func(*args, **kwargs)
TypeError: merge_all_data() got an unexpected keyword argument 'conf'
[2025-06-06T19:43:41.655+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_music_pipeline, task_id=merge_data, execution_date=20250606T192856, start_date=20250606T194341, end_date=20250606T194341
[2025-06-06T19:43:41.663+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 94 for task merge_data (merge_all_data() got an unexpected keyword argument 'conf'; 2525)
[2025-06-06T19:43:41.679+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-06T19:43:41.696+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
